//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KP.Online.API.SaleOrder_WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISaleOrderService", Namespace="http://tempuri.org/")]
    public partial class SaleOrderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateAllowSaleOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOrderOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOrderOnlineJsonOperationCompleted;
        
        private System.Threading.SendOrPostCallback HoleOrderOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelOrderOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoidOrderOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompleteOrderOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderOnlineOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderOnlineListOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateStatusOrderOnlineOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SaleOrderService() {
            this.Url = global::KP.Online.API.Properties.Settings.Default.KP_Online_API_SaleOrder_WebService_SaleOrderService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateAllowSaleOnlineCompletedEventHandler ValidateAllowSaleOnlineCompleted;
        
        /// <remarks/>
        public event SaveOrderOnlineCompletedEventHandler SaveOrderOnlineCompleted;
        
        /// <remarks/>
        public event SaveOrderOnlineJsonCompletedEventHandler SaveOrderOnlineJsonCompleted;
        
        /// <remarks/>
        public event HoleOrderOnlineCompletedEventHandler HoleOrderOnlineCompleted;
        
        /// <remarks/>
        public event CancelOrderOnlineCompletedEventHandler CancelOrderOnlineCompleted;
        
        /// <remarks/>
        public event VoidOrderOnlineCompletedEventHandler VoidOrderOnlineCompleted;
        
        /// <remarks/>
        public event CompleteOrderOnlineCompletedEventHandler CompleteOrderOnlineCompleted;
        
        /// <remarks/>
        public event GetOrderOnlineCompletedEventHandler GetOrderOnlineCompleted;
        
        /// <remarks/>
        public event GetOrderOnlineListCompletedEventHandler GetOrderOnlineListCompleted;
        
        /// <remarks/>
        public event UpdateStatusOrderOnlineCompletedEventHandler UpdateStatusOrderOnlineCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/ValidateAllowSaleOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SaleAmountByPassport ValidateAllowSaleOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string airport_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string passort, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string dateString, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string flight_code) {
            object[] results = this.Invoke("ValidateAllowSaleOnline", new object[] {
                        airport_code,
                        passort,
                        dateString,
                        flight_code});
            return ((SaleAmountByPassport)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateAllowSaleOnlineAsync(string airport_code, string passort, string dateString, string flight_code) {
            this.ValidateAllowSaleOnlineAsync(airport_code, passort, dateString, flight_code, null);
        }
        
        /// <remarks/>
        public void ValidateAllowSaleOnlineAsync(string airport_code, string passort, string dateString, string flight_code, object userState) {
            if ((this.ValidateAllowSaleOnlineOperationCompleted == null)) {
                this.ValidateAllowSaleOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateAllowSaleOnlineOperationCompleted);
            }
            this.InvokeAsync("ValidateAllowSaleOnline", new object[] {
                        airport_code,
                        passort,
                        dateString,
                        flight_code}, this.ValidateAllowSaleOnlineOperationCompleted, userState);
        }
        
        private void OnValidateAllowSaleOnlineOperationCompleted(object arg) {
            if ((this.ValidateAllowSaleOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateAllowSaleOnlineCompleted(this, new ValidateAllowSaleOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/SaveOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession SaveOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OrderHeader order) {
            object[] results = this.Invoke("SaveOrderOnline", new object[] {
                        order});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOrderOnlineAsync(OrderHeader order) {
            this.SaveOrderOnlineAsync(order, null);
        }
        
        /// <remarks/>
        public void SaveOrderOnlineAsync(OrderHeader order, object userState) {
            if ((this.SaveOrderOnlineOperationCompleted == null)) {
                this.SaveOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("SaveOrderOnline", new object[] {
                        order}, this.SaveOrderOnlineOperationCompleted, userState);
        }
        
        private void OnSaveOrderOnlineOperationCompleted(object arg) {
            if ((this.SaveOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOrderOnlineCompleted(this, new SaveOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/SaveOrderOnlineJson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession SaveOrderOnlineJson([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string orderJson) {
            object[] results = this.Invoke("SaveOrderOnlineJson", new object[] {
                        orderJson});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void SaveOrderOnlineJsonAsync(string orderJson) {
            this.SaveOrderOnlineJsonAsync(orderJson, null);
        }
        
        /// <remarks/>
        public void SaveOrderOnlineJsonAsync(string orderJson, object userState) {
            if ((this.SaveOrderOnlineJsonOperationCompleted == null)) {
                this.SaveOrderOnlineJsonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOrderOnlineJsonOperationCompleted);
            }
            this.InvokeAsync("SaveOrderOnlineJson", new object[] {
                        orderJson}, this.SaveOrderOnlineJsonOperationCompleted, userState);
        }
        
        private void OnSaveOrderOnlineJsonOperationCompleted(object arg) {
            if ((this.SaveOrderOnlineJsonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveOrderOnlineJsonCompleted(this, new SaveOrderOnlineJsonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/HoleOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession HoleOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order) {
            object[] results = this.Invoke("HoleOrderOnline", new object[] {
                        order});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void HoleOrderOnlineAsync(string order) {
            this.HoleOrderOnlineAsync(order, null);
        }
        
        /// <remarks/>
        public void HoleOrderOnlineAsync(string order, object userState) {
            if ((this.HoleOrderOnlineOperationCompleted == null)) {
                this.HoleOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHoleOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("HoleOrderOnline", new object[] {
                        order}, this.HoleOrderOnlineOperationCompleted, userState);
        }
        
        private void OnHoleOrderOnlineOperationCompleted(object arg) {
            if ((this.HoleOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HoleOrderOnlineCompleted(this, new HoleOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/CancelOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession CancelOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_no) {
            object[] results = this.Invoke("CancelOrderOnline", new object[] {
                        order_no});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void CancelOrderOnlineAsync(string order_no) {
            this.CancelOrderOnlineAsync(order_no, null);
        }
        
        /// <remarks/>
        public void CancelOrderOnlineAsync(string order_no, object userState) {
            if ((this.CancelOrderOnlineOperationCompleted == null)) {
                this.CancelOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("CancelOrderOnline", new object[] {
                        order_no}, this.CancelOrderOnlineOperationCompleted, userState);
        }
        
        private void OnCancelOrderOnlineOperationCompleted(object arg) {
            if ((this.CancelOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelOrderOnlineCompleted(this, new CancelOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/VoidOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession VoidOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_no) {
            object[] results = this.Invoke("VoidOrderOnline", new object[] {
                        order_no});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void VoidOrderOnlineAsync(string order_no) {
            this.VoidOrderOnlineAsync(order_no, null);
        }
        
        /// <remarks/>
        public void VoidOrderOnlineAsync(string order_no, object userState) {
            if ((this.VoidOrderOnlineOperationCompleted == null)) {
                this.VoidOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoidOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("VoidOrderOnline", new object[] {
                        order_no}, this.VoidOrderOnlineOperationCompleted, userState);
        }
        
        private void OnVoidOrderOnlineOperationCompleted(object arg) {
            if ((this.VoidOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoidOrderOnlineCompleted(this, new VoidOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/CompleteOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession CompleteOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_no) {
            object[] results = this.Invoke("CompleteOrderOnline", new object[] {
                        order_no});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void CompleteOrderOnlineAsync(string order_no) {
            this.CompleteOrderOnlineAsync(order_no, null);
        }
        
        /// <remarks/>
        public void CompleteOrderOnlineAsync(string order_no, object userState) {
            if ((this.CompleteOrderOnlineOperationCompleted == null)) {
                this.CompleteOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompleteOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("CompleteOrderOnline", new object[] {
                        order_no}, this.CompleteOrderOnlineOperationCompleted, userState);
        }
        
        private void OnCompleteOrderOnlineOperationCompleted(object arg) {
            if ((this.CompleteOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompleteOrderOnlineCompleted(this, new CompleteOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/GetOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession GetOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_no) {
            object[] results = this.Invoke("GetOrderOnline", new object[] {
                        order_no});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderOnlineAsync(string order_no) {
            this.GetOrderOnlineAsync(order_no, null);
        }
        
        /// <remarks/>
        public void GetOrderOnlineAsync(string order_no, object userState) {
            if ((this.GetOrderOnlineOperationCompleted == null)) {
                this.GetOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("GetOrderOnline", new object[] {
                        order_no}, this.GetOrderOnlineOperationCompleted, userState);
        }
        
        private void OnGetOrderOnlineOperationCompleted(object arg) {
            if ((this.GetOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderOnlineCompleted(this, new GetOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/GetOrderOnlineList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
        public OrderSession[] GetOrderOnlineList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string airport_code, int skip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool skipSpecified, int take, [System.Xml.Serialization.XmlIgnoreAttribute()] bool takeSpecified) {
            object[] results = this.Invoke("GetOrderOnlineList", new object[] {
                        airport_code,
                        skip,
                        skipSpecified,
                        take,
                        takeSpecified});
            return ((OrderSession[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderOnlineListAsync(string airport_code, int skip, bool skipSpecified, int take, bool takeSpecified) {
            this.GetOrderOnlineListAsync(airport_code, skip, skipSpecified, take, takeSpecified, null);
        }
        
        /// <remarks/>
        public void GetOrderOnlineListAsync(string airport_code, int skip, bool skipSpecified, int take, bool takeSpecified, object userState) {
            if ((this.GetOrderOnlineListOperationCompleted == null)) {
                this.GetOrderOnlineListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderOnlineListOperationCompleted);
            }
            this.InvokeAsync("GetOrderOnlineList", new object[] {
                        airport_code,
                        skip,
                        skipSpecified,
                        take,
                        takeSpecified}, this.GetOrderOnlineListOperationCompleted, userState);
        }
        
        private void OnGetOrderOnlineListOperationCompleted(object arg) {
            if ((this.GetOrderOnlineListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderOnlineListCompleted(this, new GetOrderOnlineListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISaleOrderService/UpdateStatusOrderOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OrderSession UpdateStatusOrderOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_no, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string status) {
            object[] results = this.Invoke("UpdateStatusOrderOnline", new object[] {
                        order_no,
                        status});
            return ((OrderSession)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateStatusOrderOnlineAsync(string order_no, string status) {
            this.UpdateStatusOrderOnlineAsync(order_no, status, null);
        }
        
        /// <remarks/>
        public void UpdateStatusOrderOnlineAsync(string order_no, string status, object userState) {
            if ((this.UpdateStatusOrderOnlineOperationCompleted == null)) {
                this.UpdateStatusOrderOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateStatusOrderOnlineOperationCompleted);
            }
            this.InvokeAsync("UpdateStatusOrderOnline", new object[] {
                        order_no,
                        status}, this.UpdateStatusOrderOnlineOperationCompleted, userState);
        }
        
        private void OnUpdateStatusOrderOnlineOperationCompleted(object arg) {
            if ((this.UpdateStatusOrderOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateStatusOrderOnlineCompleted(this, new UpdateStatusOrderOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class SaleAmountByPassport {
        
        private System.Nullable<decimal> alcoholField;
        
        private bool alcoholFieldSpecified;
        
        private System.Nullable<decimal> saleAmtField;
        
        private bool saleAmtFieldSpecified;
        
        private System.Nullable<decimal> tobaccoField;
        
        private bool tobaccoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Alcohol {
            get {
                return this.alcoholField;
            }
            set {
                this.alcoholField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlcoholSpecified {
            get {
                return this.alcoholFieldSpecified;
            }
            set {
                this.alcoholFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SaleAmt {
            get {
                return this.saleAmtField;
            }
            set {
                this.saleAmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleAmtSpecified {
            get {
                return this.saleAmtFieldSpecified;
            }
            set {
                this.saleAmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Tobacco {
            get {
                return this.tobaccoField;
            }
            set {
                this.tobaccoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TobaccoSpecified {
            get {
                return this.tobaccoFieldSpecified;
            }
            set {
                this.tobaccoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class OrderSession {
        
        private string pOSInvoiceNoField;
        
        private string pOSOrderNoField;
        
        private string pOSSessionKeyField;
        
        private string pOSStatusField;
        
        private string saleOrderNoField;
        
        private string saleOrderStatusField;
        
        private string sessionGuidField;
        
        private long sessionIdField;
        
        private bool sessionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string POSInvoiceNo {
            get {
                return this.pOSInvoiceNoField;
            }
            set {
                this.pOSInvoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string POSOrderNo {
            get {
                return this.pOSOrderNoField;
            }
            set {
                this.pOSOrderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string POSSessionKey {
            get {
                return this.pOSSessionKeyField;
            }
            set {
                this.pOSSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string POSStatus {
            get {
                return this.pOSStatusField;
            }
            set {
                this.pOSStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SaleOrderNo {
            get {
                return this.saleOrderNoField;
            }
            set {
                this.saleOrderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SaleOrderStatus {
            get {
                return this.saleOrderStatusField;
            }
            set {
                this.saleOrderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string SessionGuid {
            get {
                return this.sessionGuidField;
            }
            set {
                this.sessionGuidField = value;
            }
        }
        
        /// <remarks/>
        public long SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SessionIdSpecified {
            get {
                return this.sessionIdFieldSpecified;
            }
            set {
                this.sessionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class Payment {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string codeField;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class Order {
        
        private string agentCodeField;
        
        private string deliveryCostField;
        
        private string dutyTaxField;
        
        private string invoiceNoField;
        
        private bool isAcceptMediaField;
        
        private bool isAcceptMediaFieldSpecified;
        
        private string memberIDField;
        
        private string orderNoField;
        
        private string paymentNoField;
        
        private string remarksField;
        
        private string userTokenField;
        
        private string weChatIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgentCode {
            get {
                return this.agentCodeField;
            }
            set {
                this.agentCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryCost {
            get {
                return this.deliveryCostField;
            }
            set {
                this.deliveryCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DutyTax {
            get {
                return this.dutyTaxField;
            }
            set {
                this.dutyTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAcceptMedia {
            get {
                return this.isAcceptMediaField;
            }
            set {
                this.isAcceptMediaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAcceptMediaSpecified {
            get {
                return this.isAcceptMediaFieldSpecified;
            }
            set {
                this.isAcceptMediaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MemberID {
            get {
                return this.memberIDField;
            }
            set {
                this.memberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PaymentNo {
            get {
                return this.paymentNoField;
            }
            set {
                this.paymentNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WeChatID {
            get {
                return this.weChatIDField;
            }
            set {
                this.weChatIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class ItemSKU {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal discountField;
        
        private bool discountFieldSpecified;
        
        private decimal discountPerField;
        
        private bool discountPerFieldSpecified;
        
        private decimal discountRateField;
        
        private bool discountRateFieldSpecified;
        
        private string materialCodeField;
        
        private decimal netField;
        
        private bool netFieldSpecified;
        
        private string promoCodeField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string recNoField;
        
        private decimal sPDiscountField;
        
        private bool sPDiscountFieldSpecified;
        
        private decimal sPDiscountPerField;
        
        private bool sPDiscountPerFieldSpecified;
        
        private decimal sPDiscountRateField;
        
        private bool sPDiscountRateFieldSpecified;
        
        private string sPPromoCodeField;
        
        private string sellerAdjustFeeField;
        
        private decimal sellingPriceField;
        
        private bool sellingPriceFieldSpecified;
        
        private string subOrderTypeField;
        
        private decimal totalDiscountField;
        
        private bool totalDiscountFieldSpecified;
        
        private decimal totalNetField;
        
        private bool totalNetFieldSpecified;
        
        private string ord_noField;
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountSpecified {
            get {
                return this.discountFieldSpecified;
            }
            set {
                this.discountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountPer {
            get {
                return this.discountPerField;
            }
            set {
                this.discountPerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountPerSpecified {
            get {
                return this.discountPerFieldSpecified;
            }
            set {
                this.discountPerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal DiscountRate {
            get {
                return this.discountRateField;
            }
            set {
                this.discountRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DiscountRateSpecified {
            get {
                return this.discountRateFieldSpecified;
            }
            set {
                this.discountRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MaterialCode {
            get {
                return this.materialCodeField;
            }
            set {
                this.materialCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Net {
            get {
                return this.netField;
            }
            set {
                this.netField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetSpecified {
            get {
                return this.netFieldSpecified;
            }
            set {
                this.netFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PromoCode {
            get {
                return this.promoCodeField;
            }
            set {
                this.promoCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecNo {
            get {
                return this.recNoField;
            }
            set {
                this.recNoField = value;
            }
        }
        
        /// <remarks/>
        public decimal SPDiscount {
            get {
                return this.sPDiscountField;
            }
            set {
                this.sPDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPDiscountSpecified {
            get {
                return this.sPDiscountFieldSpecified;
            }
            set {
                this.sPDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SPDiscountPer {
            get {
                return this.sPDiscountPerField;
            }
            set {
                this.sPDiscountPerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPDiscountPerSpecified {
            get {
                return this.sPDiscountPerFieldSpecified;
            }
            set {
                this.sPDiscountPerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SPDiscountRate {
            get {
                return this.sPDiscountRateField;
            }
            set {
                this.sPDiscountRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPDiscountRateSpecified {
            get {
                return this.sPDiscountRateFieldSpecified;
            }
            set {
                this.sPDiscountRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SPPromoCode {
            get {
                return this.sPPromoCodeField;
            }
            set {
                this.sPPromoCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SellerAdjustFee {
            get {
                return this.sellerAdjustFeeField;
            }
            set {
                this.sellerAdjustFeeField = value;
            }
        }
        
        /// <remarks/>
        public decimal SellingPrice {
            get {
                return this.sellingPriceField;
            }
            set {
                this.sellingPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SellingPriceSpecified {
            get {
                return this.sellingPriceFieldSpecified;
            }
            set {
                this.sellingPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubOrderType {
            get {
                return this.subOrderTypeField;
            }
            set {
                this.subOrderTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalDiscount {
            get {
                return this.totalDiscountField;
            }
            set {
                this.totalDiscountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalDiscountSpecified {
            get {
                return this.totalDiscountFieldSpecified;
            }
            set {
                this.totalDiscountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalNet {
            get {
                return this.totalNetField;
            }
            set {
                this.totalNetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalNetSpecified {
            get {
                return this.totalNetFieldSpecified;
            }
            set {
                this.totalNetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ord_no {
            get {
                return this.ord_noField;
            }
            set {
                this.ord_noField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class FlightWeekDays {
        
        private string fullNameField;
        
        private string shortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class FlightTime {
        
        private string time24Field;
        
        private string timeAMPMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Time24 {
            get {
                return this.time24Field;
            }
            set {
                this.time24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimeAMPM {
            get {
                return this.timeAMPMField;
            }
            set {
                this.timeAMPMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class PickUp {
        
        private string codeField;
        
        private string detailField;
        
        private string mapImgField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MapImg {
            get {
                return this.mapImgField;
            }
            set {
                this.mapImgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class Flight {
        
        private string airlineCodeField;
        
        private string airlineNameField;
        
        private string airportCodeField;
        
        private string arrivalAirportField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string departureAirportField;
        
        private string flightCodeField;
        
        private string flightDescField;
        
        private PickUp pickUpField;
        
        private string terminalField;
        
        private FlightTime timeField;
        
        private FlightWeekDays[] weekDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirlineName {
            get {
                return this.airlineNameField;
            }
            set {
                this.airlineNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlightCode {
            get {
                return this.flightCodeField;
            }
            set {
                this.flightCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlightDesc {
            get {
                return this.flightDescField;
            }
            set {
                this.flightDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PickUp PickUp {
            get {
                return this.pickUpField;
            }
            set {
                this.pickUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FlightWeekDays[] WeekDays {
            get {
                return this.weekDaysField;
            }
            set {
                this.weekDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class Billing {
        
        private string billAddress1Field;
        
        private string billAddress2Field;
        
        private string billAddress3Field;
        
        private string birthdayField;
        
        private string cityField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private string districtField;
        
        private string emailField;
        
        private string faxField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mobilePhoneField;
        
        private string passportNoField;
        
        private string personalTitleField;
        
        private string phoneCountryCodeField;
        
        private string postalCodeField;
        
        private string provinceField;
        
        private string sexField;
        
        private string streetField;
        
        private string telephoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BillAddress1 {
            get {
                return this.billAddress1Field;
            }
            set {
                this.billAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BillAddress2 {
            get {
                return this.billAddress2Field;
            }
            set {
                this.billAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BillAddress3 {
            get {
                return this.billAddress3Field;
            }
            set {
                this.billAddress3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PassportNo {
            get {
                return this.passportNoField;
            }
            set {
                this.passportNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PersonalTitle {
            get {
                return this.personalTitleField;
            }
            set {
                this.personalTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneCountryCode {
            get {
                return this.phoneCountryCodeField;
            }
            set {
                this.phoneCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class OrderHeader {
        
        private Billing billingField;
        
        private Flight flightField;
        
        private ItemSKU[] itemsField;
        
        private Order newOrderField;
        
        private Payment[] paymentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Billing Billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Flight Flight {
            get {
                return this.flightField;
            }
            set {
                this.flightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItemSKU[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Order NewOrder {
            get {
                return this.newOrderField;
            }
            set {
                this.newOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Payment[] Payments {
            get {
                return this.paymentsField;
            }
            set {
                this.paymentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateAllowSaleOnlineCompletedEventHandler(object sender, ValidateAllowSaleOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateAllowSaleOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateAllowSaleOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaleAmountByPassport Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaleAmountByPassport)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SaveOrderOnlineCompletedEventHandler(object sender, SaveOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SaveOrderOnlineJsonCompletedEventHandler(object sender, SaveOrderOnlineJsonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveOrderOnlineJsonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveOrderOnlineJsonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HoleOrderOnlineCompletedEventHandler(object sender, HoleOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HoleOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HoleOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CancelOrderOnlineCompletedEventHandler(object sender, CancelOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VoidOrderOnlineCompletedEventHandler(object sender, VoidOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoidOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoidOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CompleteOrderOnlineCompletedEventHandler(object sender, CompleteOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompleteOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompleteOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOrderOnlineCompletedEventHandler(object sender, GetOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetOrderOnlineListCompletedEventHandler(object sender, GetOrderOnlineListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderOnlineListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderOnlineListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateStatusOrderOnlineCompletedEventHandler(object sender, UpdateStatusOrderOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateStatusOrderOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateStatusOrderOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderSession Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderSession)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591