//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace KP.Online.API.WCF {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IOtherService", Namespace="http://tempuri.org/")]
    public partial class OtherService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckFlightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckFlightsByOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataFlightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataDepartureOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataArrivalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaleQueueOnlineOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OtherService() {
            this.Url = global::KP.Online.API.Properties.Settings.Default.KP_OrderMGT_API_WCF_OtherService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckFlightsCompletedEventHandler CheckFlightsCompleted;
        
        /// <remarks/>
        public event CheckFlightsByCompletedEventHandler CheckFlightsByCompleted;
        
        /// <remarks/>
        public event GetDataFlightsCompletedEventHandler GetDataFlightsCompleted;
        
        /// <remarks/>
        public event GetDataAllCompletedEventHandler GetDataAllCompleted;
        
        /// <remarks/>
        public event GetDataDepartureCompletedEventHandler GetDataDepartureCompleted;
        
        /// <remarks/>
        public event GetDataArrivalCompletedEventHandler GetDataArrivalCompleted;
        
        /// <remarks/>
        public event GetDataTransferCompletedEventHandler GetDataTransferCompleted;
        
        /// <remarks/>
        public event SaleQueueOnlineCompletedEventHandler SaleQueueOnlineCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/CheckFlights", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Flight CheckFlights([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fight_code) {
            object[] results = this.Invoke("CheckFlights", new object[] {
                        fight_code});
            return ((Flight)(results[0]));
        }
        
        /// <remarks/>
        public void CheckFlightsAsync(string fight_code) {
            this.CheckFlightsAsync(fight_code, null);
        }
        
        /// <remarks/>
        public void CheckFlightsAsync(string fight_code, object userState) {
            if ((this.CheckFlightsOperationCompleted == null)) {
                this.CheckFlightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckFlightsOperationCompleted);
            }
            this.InvokeAsync("CheckFlights", new object[] {
                        fight_code}, this.CheckFlightsOperationCompleted, userState);
        }
        
        private void OnCheckFlightsOperationCompleted(object arg) {
            if ((this.CheckFlightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckFlightsCompleted(this, new CheckFlightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/CheckFlightsBy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Flight CheckFlightsBy([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fight_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fight_date) {
            object[] results = this.Invoke("CheckFlightsBy", new object[] {
                        fight_code,
                        fight_date});
            return ((Flight)(results[0]));
        }
        
        /// <remarks/>
        public void CheckFlightsByAsync(string fight_code, string fight_date) {
            this.CheckFlightsByAsync(fight_code, fight_date, null);
        }
        
        /// <remarks/>
        public void CheckFlightsByAsync(string fight_code, string fight_date, object userState) {
            if ((this.CheckFlightsByOperationCompleted == null)) {
                this.CheckFlightsByOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckFlightsByOperationCompleted);
            }
            this.InvokeAsync("CheckFlightsBy", new object[] {
                        fight_code,
                        fight_date}, this.CheckFlightsByOperationCompleted, userState);
        }
        
        private void OnCheckFlightsByOperationCompleted(object arg) {
            if ((this.CheckFlightsByCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckFlightsByCompleted(this, new CheckFlightsByCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/GetDataFlights", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Flight GetDataFlights([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string fight_code) {
            object[] results = this.Invoke("GetDataFlights", new object[] {
                        fight_code});
            return ((Flight)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataFlightsAsync(string fight_code) {
            this.GetDataFlightsAsync(fight_code, null);
        }
        
        /// <remarks/>
        public void GetDataFlightsAsync(string fight_code, object userState) {
            if ((this.GetDataFlightsOperationCompleted == null)) {
                this.GetDataFlightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataFlightsOperationCompleted);
            }
            this.InvokeAsync("GetDataFlights", new object[] {
                        fight_code}, this.GetDataFlightsOperationCompleted, userState);
        }
        
        private void OnGetDataFlightsOperationCompleted(object arg) {
            if ((this.GetDataFlightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataFlightsCompleted(this, new GetDataFlightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/GetDataAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightsAll GetDataAll() {
            object[] results = this.Invoke("GetDataAll", new object[0]);
            return ((FlightsAll)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAllAsync() {
            this.GetDataAllAsync(null);
        }
        
        /// <remarks/>
        public void GetDataAllAsync(object userState) {
            if ((this.GetDataAllOperationCompleted == null)) {
                this.GetDataAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataAllOperationCompleted);
            }
            this.InvokeAsync("GetDataAll", new object[0], this.GetDataAllOperationCompleted, userState);
        }
        
        private void OnGetDataAllOperationCompleted(object arg) {
            if ((this.GetDataAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataAllCompleted(this, new GetDataAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/GetDataDeparture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
        public Flight[] GetDataDeparture() {
            object[] results = this.Invoke("GetDataDeparture", new object[0]);
            return ((Flight[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataDepartureAsync() {
            this.GetDataDepartureAsync(null);
        }
        
        /// <remarks/>
        public void GetDataDepartureAsync(object userState) {
            if ((this.GetDataDepartureOperationCompleted == null)) {
                this.GetDataDepartureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataDepartureOperationCompleted);
            }
            this.InvokeAsync("GetDataDeparture", new object[0], this.GetDataDepartureOperationCompleted, userState);
        }
        
        private void OnGetDataDepartureOperationCompleted(object arg) {
            if ((this.GetDataDepartureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataDepartureCompleted(this, new GetDataDepartureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/GetDataArrival", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
        public Flight[] GetDataArrival() {
            object[] results = this.Invoke("GetDataArrival", new object[0]);
            return ((Flight[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataArrivalAsync() {
            this.GetDataArrivalAsync(null);
        }
        
        /// <remarks/>
        public void GetDataArrivalAsync(object userState) {
            if ((this.GetDataArrivalOperationCompleted == null)) {
                this.GetDataArrivalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataArrivalOperationCompleted);
            }
            this.InvokeAsync("GetDataArrival", new object[0], this.GetDataArrivalOperationCompleted, userState);
        }
        
        private void OnGetDataArrivalOperationCompleted(object arg) {
            if ((this.GetDataArrivalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataArrivalCompleted(this, new GetDataArrivalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/GetDataTransfer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
        public Flight[] GetDataTransfer() {
            object[] results = this.Invoke("GetDataTransfer", new object[0]);
            return ((Flight[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataTransferAsync() {
            this.GetDataTransferAsync(null);
        }
        
        /// <remarks/>
        public void GetDataTransferAsync(object userState) {
            if ((this.GetDataTransferOperationCompleted == null)) {
                this.GetDataTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataTransferOperationCompleted);
            }
            this.InvokeAsync("GetDataTransfer", new object[0], this.GetDataTransferOperationCompleted, userState);
        }
        
        private void OnGetDataTransferOperationCompleted(object arg) {
            if ((this.GetDataTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataTransferCompleted(this, new GetDataTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOtherService/SaleQueueOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
        public SaleQueue[] SaleQueueOnline([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string airport_code, int terminal, [System.Xml.Serialization.XmlIgnoreAttribute()] bool terminalSpecified) {
            object[] results = this.Invoke("SaleQueueOnline", new object[] {
                        airport_code,
                        terminal,
                        terminalSpecified});
            return ((SaleQueue[])(results[0]));
        }
        
        /// <remarks/>
        public void SaleQueueOnlineAsync(string airport_code, int terminal, bool terminalSpecified) {
            this.SaleQueueOnlineAsync(airport_code, terminal, terminalSpecified, null);
        }
        
        /// <remarks/>
        public void SaleQueueOnlineAsync(string airport_code, int terminal, bool terminalSpecified, object userState) {
            if ((this.SaleQueueOnlineOperationCompleted == null)) {
                this.SaleQueueOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaleQueueOnlineOperationCompleted);
            }
            this.InvokeAsync("SaleQueueOnline", new object[] {
                        airport_code,
                        terminal,
                        terminalSpecified}, this.SaleQueueOnlineOperationCompleted, userState);
        }
        
        private void OnSaleQueueOnlineOperationCompleted(object arg) {
            if ((this.SaleQueueOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaleQueueOnlineCompleted(this, new SaleQueueOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class Flight {
        
        private string airlineCodeField;
        
        private string airlineNameField;
        
        private string airportCodeField;
        
        private string arrivalAirportField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string departureAirportField;
        
        private string flightCodeField;
        
        private string flightDescField;
        
        private PickUp pickUpField;
        
        private string terminalField;
        
        private FlightTime timeField;
        
        private FlightWeekDays[] weekDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirlineName {
            get {
                return this.airlineNameField;
            }
            set {
                this.airlineNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlightCode {
            get {
                return this.flightCodeField;
            }
            set {
                this.flightCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FlightDesc {
            get {
                return this.flightDescField;
            }
            set {
                this.flightDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PickUp PickUp {
            get {
                return this.pickUpField;
            }
            set {
                this.pickUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FlightTime Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FlightWeekDays[] WeekDays {
            get {
                return this.weekDaysField;
            }
            set {
                this.weekDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class PickUp {
        
        private string codeField;
        
        private string detailField;
        
        private string mapImgField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MapImg {
            get {
                return this.mapImgField;
            }
            set {
                this.mapImgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class DetailSaleQueue {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string docNoField;
        
        private string macNoField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MacNo {
            get {
                return this.macNoField;
            }
            set {
                this.macNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class SaleQueue {
        
        private DetailSaleQueue[] detailsField;
        
        private decimal qtyField;
        
        private bool qtyFieldSpecified;
        
        private string skuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DetailSaleQueue[] details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public decimal qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qtySpecified {
            get {
                return this.qtyFieldSpecified;
            }
            set {
                this.qtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class FlightsAll {
        
        private Flight[] arrivalField;
        
        private Flight[] departureField;
        
        private Flight[] transferField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Flight[] Arrival {
            get {
                return this.arrivalField;
            }
            set {
                this.arrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Flight[] Departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Flight[] Transfer {
            get {
                return this.transferField;
            }
            set {
                this.transferField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class FlightWeekDays {
        
        private string fullNameField;
        
        private string shortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/KP.Online.BL.ServiceModel")]
    public partial class FlightTime {
        
        private string time24Field;
        
        private string timeAMPMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Time24 {
            get {
                return this.time24Field;
            }
            set {
                this.time24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TimeAMPM {
            get {
                return this.timeAMPMField;
            }
            set {
                this.timeAMPMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckFlightsCompletedEventHandler(object sender, CheckFlightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckFlightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckFlightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CheckFlightsByCompletedEventHandler(object sender, CheckFlightsByCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckFlightsByCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckFlightsByCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataFlightsCompletedEventHandler(object sender, GetDataFlightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataFlightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataFlightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataAllCompletedEventHandler(object sender, GetDataAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FlightsAll Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FlightsAll)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataDepartureCompletedEventHandler(object sender, GetDataDepartureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataDepartureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataDepartureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataArrivalCompletedEventHandler(object sender, GetDataArrivalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataArrivalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataArrivalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataTransferCompletedEventHandler(object sender, GetDataTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Flight[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Flight[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SaleQueueOnlineCompletedEventHandler(object sender, SaleQueueOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaleQueueOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaleQueueOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaleQueue[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaleQueue[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591